language: php

php:
  - 5.5
  - 5.6
  - 7

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install:
  - composer update --prefer-dist --no-interaction

script:
  - cd ./bin/scripts \
    && ./travis_phpunit.sh \
    && cd ../../

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com